Use git protocol instead of https
The git version (1.7.1) in the container is too old.
It can't access github.com with https protocol now:

error:  while accessing https://github.com/sonelli/android-ports-tools.git/info/refs

fatal: HTTP request failed

Use git protocol to avoid the error.